name: Build
on:
  push:
    branches:
      - "**"
  pull_request:
    types: [opened, reopened]

jobs:
  analysis:
    name: Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: docker://sonarsource/sonar-scanner-cli:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  e2e:
    name: E2E test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        env:
          GITHUB_PERSONAL_ACCESS_TOKEN: "abc"
          CONTACT_EMAIL_ADDRESS: "test@example.com"
          RECAPTCHA_PRIVATE_KEY: "abc"
          RECAPTCHA_SITE_KEY: "abc"
        with:
          build: npm run build
          start: npm start
